
epochs: 50
batch_size: 32
learning_rate: 0.005
weight_decay: 1e-4
print_freq: 100
save_freq: 10000
embedding_size: 50
hidden_size: 64
layers: 1
classes: 2
min_samples: 1
cuda: True
mean_seq: True
rnn: LSTM
clip: 0.25
patience: 15
max_seq_len: 20
input: simple

# directories
embed_dir: embeddings/d_word_index.pkl
saved_model_dir: saved_models/best_model