
epochs: 50
batch_size: 128
learning_rate: 0.005
weight_decay: 1e-4
print_freq: 100
save_freq: 10000
embedding_size: 50
hidden_size: 128
layers: 2
classes: 2
min_samples: 1
cuda: True
mean_seq: True
rnn: LSTM
clip: 0.25
patience: 10
max_seq_len: 250
input: normal

# directories
embed_dir: embeddings/d_word_index.pkl
saved_model_dir: saved_models/best_model